// src/features/category/mockProducts.js

export const mockProducts = [
  {
    id: 1,
    name: "트렌디한 패션 아이템 1",
    brand: "TBH",
    price: 59000,
    originalPrice: 99000,
    image: "/images/products/girl-mb-data.jpg",
    isNew: true,
    discount: 40,
    colors: ["블랙", "화이트"],
    category: "의류",
    size: ["M", "L"],
  },
  {
    id: 2,
    name: "트렌디한 패션 아이템 2",
    brand: "TBH",
    price: 129000,
    originalPrice: 159000,
    image: "/images/products/mens-mb-data.jpg",
    isNew: false,
    discount: 20,
    colors: ["네이비", "그레이", "블루"],
    category: "신발",
    size: ["S", "M", "L"],
  },
  {
    id: 3,
    name: "트렌디한 패션 아이템 3",
    brand: "TBH",
    price: 39000,
    originalPrice: 49000,
    image: "/images/products/girl-mb-data.jpg",
    isNew: true,
    discount: 15,
    colors: ["베이지", "레드"],
    category: "가방",
    size: ["FREE"],
  },
  {
    id: 4,
    name: "트렌디한 패션 아이템 4",
    brand: "TBH",
    price: 89000,
    originalPrice: 129000,
    image: "/images/products/mens-mb-data.jpg",
    isNew: false,
    discount: 30,
    colors: ["블랙", "그레이"],
    category: "액세서리",
    size: ["XS", "S"],
  },
  {
    id: 5,
    name: "트렌디한 패션 아이템 5",
    brand: "TBH",
    price: 49000,
    originalPrice: 69000,
    image: "/images/products/girl-mb-data.jpg",
    isNew: true,
    discount: 29,
    colors: ["블루", "그린"],
    category: "언더웨어",
    size: ["M", "L", "XL"],
  },
  {
    id: 6,
    name: "트렌디한 패션 아이템 6",
    brand: "TBH",
    price: 159000,
    originalPrice: 199000,
    image: "/images/products/mens-mb-data.jpg",
    isNew: false,
    discount: 20,
    colors: ["화이트", "네이비"],
    category: "스포츠웨어",
    size: ["L", "XL", "XXL"],
  },
  // ... 필요시 더 추가 ...
];

