// src/features/category/mockProducts.js

export const mockProducts = [
  {
    id: 1,
    name: "트렌디한 패션 아이템 1",
    brand: "TBH",
    price: 59000,
    originalPrice: 99000,
    image: "/images/products/girl-mb-data.jpg",
    isNew: true,
    discount: 40,
    colors: ["블랙", "화이트"],
    category: "PANTS",
    size: ["100", "105"],
  },
  {
    id: 2,
    name: "트렌디한 패션 아이템 2",
    brand: "TBH",
    price: 129000,
    originalPrice: 159000,
    image: "/images/products/mens-mb-data.jpg",
    isNew: false,
    discount: 20,
    colors: ["네이비", "그레이", "블루"],
    category: "SHOES",
    size: ["95", "100", "105"],
  },
  {
    id: 3,
    name: "트렌디한 패션 아이템 3",
    brand: "TBH",
    price: 39000,
    originalPrice: 49000,
    image: "/images/products/girl-mb-data.jpg",
    isNew: true,
    discount: 15,
    colors: ["베이지", "레드"],
    category: "OUTER",
    size: ["FREE"],
  },
  {
    id: 4,
    name: "트렌디한 패션 아이템 4",
    brand: "TBH",
    price: 89000,
    originalPrice: 129000,
    image: "/images/products/mens-mb-data.jpg",
    isNew: false,
    discount: 30,
    colors: ["블랙", "그레이"],
    category: "TOP",
    size: ["90", "95"],
  },
  {
    id: 5,
    name: "트렌디한 패션 아이템 5",
    brand: "TBH",
    price: 49000,
    originalPrice: 69000,
    image: "/images/products/girl-mb-data.jpg",
    isNew: true,
    discount: 29,
    colors: ["블루", "그린"],
    category: "TOP",
    size: ["100", "105", "110"],
  },
  {
    id: 6,
    name: "트렌디한 패션 아이템 6",
    brand: "TBH",
    price: 159000,
    originalPrice: 199000,
    image: "/images/products/mens-mb-data.jpg",
    isNew: false,
    discount: 20,
    colors: ["화이트", "네이비"],
    category: "OUTER",
    size: ["105", "110"],
  },
  // ... 필요시 더 추가 ...
];
